### PR TITLE
ENH/API: bit_array_get_bits

### PR DESCRIPTION
**Pull request by wasade**
A method to get the index positions of the set bits within a `BIT_ARRAY`. This method arose as I needed to interrogate individual bits frequently. The function overhead of making calls to `bit_array_get_bit` was very large in my application, and this was an easy performance improvement.

There may be more efficient ways of doing this method, such as checking doing lookups based on the bit patterns for a given word or byte, but I'm not able to explore at this time.

Thank you @noporpoise for this library -- it has been very enjoyable to use.

### CODE REVIEW

**Comment by wasade** [comment]
The build is failing with appveyor, but given the error I think it is a fault of the build system? I'm not familiar with appveyor, so I'm not sure how to proceed there.

**Comment by noporpoise** [comment]
**Sorry**, appveyor shouldn't be showing up as it hasn't been setup. 

To avoid the function call overhead, just use the following macro to test a bit:

    bit_array_get(arr, i)

similarly, there are also macros for:

    bit_array_set(arr, i)
    bit_array_clear(arr, i)
    bit_array_toggle(arr, i)
    bit_array_assign(arr, i, v)

I think the macros should be suitable for performance so am going to close this issue. Please re-open if you still see a need for this functionality.

**Comment by wasade** [comment]
@noporpoise, I would appreciate reopening. The reason is I'm exposing this method via Cython and cannot use the macros directly. It's use is within a nested forloop and the overhead is appreciable. However, since the purpose is convenience for Cython, I can understand why you may prefer to not have it in master.

**Comment by noporpoise** [comment]
@wasade That's good enough for me. I've merged in your commit. I've added a `start` index argument to the the function `bit_array_get_bits()` and moved it to be beside similar functions `bit_array_{set,clear,toggle}_bits()`. I also added some tests for it.
Thanks for contributing.

**Comment by wasade** [comment]
Great, thank you so much!

**Comment by wasade** [comment]
Also, thank you for adding the tests. I apologize for not doing so, I overlooked where the tests were supposed to go

**Pull request closed without merging**
